### ISSUE TITLE
访问kibana报错

### ISSUE THREAD

**Issue by colinjuang** [Mikaelemmmm/go-zero-looklook#160]
elasticsearch Version: 8.12.2
kibana:8.12.2

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at js (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:425:90743)
    at Fc (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:425:103505)
    at t.unstable_runWithPriority (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:433:3768)
    at Vo (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:425:44978)
    at Bc (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:425:101427)
    at wc (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:425:96691)
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:425:45201
    at t.unstable_runWithPriority (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:433:3768)
    at Vo (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:425:44978)
    at Qo (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:425:45146)

The above error occurred in t:

    at t (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:1:2324289)
    at span
    at p
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:174050
    at m (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:150497)
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:174050
    at div
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:174050
    at z (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:24954)
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:174050
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:372:21560
    at U (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.chunk.1.js:1:13720)
    at Q (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.chunk.1.js:1:19830)
    at div
    at div
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:174050
    at p (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:294:11288)
    at O (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.chunk.1.js:1:1131)
    at div
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:174050
    at http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:60153
    at E (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.chunk.1.js:1:425)
    at he (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.chunk.1.js:1:25227)
    at t.default (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.chunk.1.js:1:30273)
    at Suspense
    at s
    at Provider (http://x.x.x.x:5601/70281/bundles/plugin/kibanaReact/1.0.0/kibanaReact.plugin.js:1:28354)
    at x (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:1:2304404)
    at L (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:1:2305205)
    at m (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:1:2300132)
    at c (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:229657)
    at Me (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:1:2326554)
    at t (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:1:2318029)
    at Re (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:1:2326997)
    at Context (http://x.x.x.x:5601/70281/bundles/core/core.entry.js:1:265045)
    at p (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:619897)
    at d (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:243384)
    at v (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:174494)
    at a (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:377:1600481)
    at w (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:352239)
    at s (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:372:189723)
    at a (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:384:349191)
    at m (http://x.x.x.x:5601/70281/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:377:1070914)
    at O (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.plugin.js:1:10228)
    at w (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.plugin.js:1:10535)
    at P (http://x.x.x.x:5601/70281/bundles/plugin/dataViewEditor/1.0.0/dataViewEditor.plugin.js:1:10634)

**Comment by Mikaelemmmm** [comment]
这个我这边反复几次都没有出现？ 把容器删除重启一下实时？
